
import 'dart:typed_data';

class Order {
    String? orderId;
    dynamic userId;
    String? agencyId;
    String? serviceType;
    String? nameSender;
    String? phoneNumberSender;
    String? nameReceiver;
    String? phoneNumberReceiver;
    int? id;
    int? mass;
    int? height;
    int? width;
    int? length;
    String? provinceSource;
    dynamic districtSource;
    String? wardSource;
    String? detailSource;
    double? longSource;
    double? latSource;
    String? provinceDest;
    String? districtDest;
    String? wardDest;
    String? detailDest;
    double? longDestination;
    double? latDestination;
    int? fee;
    dynamic parent;
    dynamic journey;
    int? cod;
    String? shipper;
    int? statusCode;
    int? miss;
    List<dynamic>? sendImages;
    List<dynamic>? receiveImages;
    dynamic sendSignature;
    dynamic receiveSignature;
    List<Uint8List>? sendImgs = [];
    List<Uint8List>? receiveImgs = [];
    Uint8List? sendSig = Uint8List.fromList([]);
    Uint8List? receiveSig = Uint8List.fromList([]);
    dynamic qrcode;
    dynamic signature;
    bool? paid;
    String? createdAt;
    String? lastUpdate;
    int? orderCode;

    Order({this.orderId, this.userId, this.agencyId, this.serviceType, this.nameSender, this.phoneNumberSender, this.nameReceiver, this.phoneNumberReceiver, this.mass, this.height, this.width, this.length, this.provinceSource, this.districtSource, this.wardSource, this.detailSource, this.longSource, this.latSource, this.provinceDest, this.districtDest, this.wardDest, this.detailDest, this.longDestination, this.latDestination, this.fee, this.parent, this.journey, this.cod, this.shipper, this.statusCode, this.miss, this.sendImages, this.receiveImages, this.sendSignature, this.receiveSignature, this.qrcode, this.signature, this.paid, this.createdAt, this.lastUpdate, this.orderCode});

    Order.fromJson(Map<String, dynamic> json) {
        orderId = json["orderId"];
        userId = json["userId"];
        agencyId = json["agencyId"];
        serviceType = json["serviceType"];
        nameSender = json["nameSender"];
        phoneNumberSender = json["phoneNumberSender"];
        nameReceiver = json["nameReceiver"];
        phoneNumberReceiver = json["phoneNumberReceiver"];
        mass = (json["mass"]).toInt();;
        height = (json["height"]).toInt();;
        width = (json["width"]).toInt();;
        length = (json["length"]).toInt();;
        provinceSource = json["provinceSource"];
        districtSource = json["districtSource"];
        wardSource = json["wardSource"];
        detailSource = json["detailSource"];
        longSource = json["longSource"];
        latSource = json["latSource"];
        provinceDest = json["provinceDest"];
        districtDest = json["districtDest"];
        wardDest = json["wardDest"];
        detailDest = json["detailDest"];
        longDestination = json["longDestination"];
        latDestination = json["latDestination"];
        fee = json["fee"].toInt();
        parent = json["parent"];
        journey = json["journey"];
        cod = json["cod"].toInt();;
        shipper = json["shipper"];
        statusCode = json["statusCode"];
        miss = json["miss"];
        print(json["sendImages"]);
        sendImages = json["sendImages"];
        receiveImages = json["receiveImages"];
        sendSignature = json["sendSignature"];
        receiveSignature = json["receiveSignature"];
        qrcode = json["qrcode"];
        signature = json["signature"];
        paid = json["paid"];
        createdAt = json["createdAt"];
        lastUpdate = json["lastUpdate"];
        orderCode = json["orderCode"];
    }

    Map<String, dynamic> toJson() {
        final Map<String, dynamic> _data = <String, dynamic>{};
        _data["orderId"] = orderId;
        _data["userId"] = userId;
        _data["agencyId"] = agencyId;
        _data["serviceType"] = serviceType;
        _data["nameSender"] = nameSender;
        _data["phoneNumberSender"] = phoneNumberSender;
        _data["nameReceiver"] = nameReceiver;
        _data["phoneNumberReceiver"] = phoneNumberReceiver;
        _data["mass"] = mass;
        _data["height"] = height;
        _data["width"] = width;
        _data["length"] = length;
        _data["provinceSource"] = provinceSource;
        _data["districtSource"] = districtSource;
        _data["wardSource"] = wardSource;
        _data["detailSource"] = detailSource;
        _data["longSource"] = longSource;
        _data["latSource"] = latSource;
        _data["provinceDest"] = provinceDest;
        _data["districtDest"] = districtDest;
        _data["wardDest"] = wardDest;
        _data["detailDest"] = detailDest;
        _data["longDestination"] = longDestination;
        _data["latDestination"] = latDestination;
        _data["fee"] = fee;
        _data["parent"] = parent;
        _data["journey"] = journey;
        _data["cod"] = cod;
        _data["shipper"] = shipper;
        _data["statusCode"] = statusCode;
        _data["miss"] = miss;
        _data["sendImages"] = sendImages;
        _data["receiveImages"] = receiveImages;
        _data["sendSignature"] = sendSignature;
        _data["receiveSignature"] = receiveSignature;
        _data["qrcode"] = qrcode;
        _data["signature"] = signature;
        _data["paid"] = paid;
        _data["createdAt"] = createdAt;
        _data["lastUpdate"] = lastUpdate;
        _data["orderCode"] = orderCode;
        return _data;
    }
}